# -*- coding: utf-8 -*-
"""Assignment 5 - Miscellaneous.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPpuqQClnOFbS5i8YlWxWy6yLnX27Pnm

# Assessment - 5 Gradable

- Each question carries 5 or 4 marks
- Marks will be assigned in terms of:

    **1. Expected output**

    **2. Quality and Explainability of code**

    ***Go back through the script and type a comment above each line explaining in English what it does.***

    **3. Copied code, if found, will result in 0 marks for that question. To avoid this make as much comments in the code to explain the approach**

### 1.

Write a Python function that prints out the first n rows of Pascal's triangle.

- Input : 5
- Output:
          1
         1 1
        1 2 1
       1 3 3 1
      1 4 6 4 1

**Very interesting video on PASCAL TRIANGLE (must watch if you are interested to know more about pascal Triangle)**
- https://www.youtube.com/watch?v=0iMtlus-afo&t=668s&ab_channel=Numberphile
"""



"""### 2.

Write a function to print following pattern

    1
    2  4
    3  6  9
    4  8  12  16
    5  10  15  20  25
    6  12  18  24  30  36
    7  14  21  28  35  42  49
    8  16  24  32  40  48  56  64
"""



"""### 3.

Write a function ``how_many_primes`` that returns the number of prime numbers that exist up to and including a given number

- how_many_primes(100) --> 25
"""



"""### 4.

b = open("assignment.txt")

Consider the code given above and write the answers to the following :

- Identify the name of the file :
- Identify the name of the function used above :
- What is 'b' in above code :
- The above statement will  ____________ file in ___________ mode.

### 5.

Accept five hobbies from the user and write in a file 'hobby.txt'. Then Read the file to list out all the 5 hobbies from the user.
"""

